version: '3'

services:
  ws-swagger-ui:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    #command: sh -c 'cd ws-swagger-ui && yarn start'
    ports:
      - '3000:3000'
    tty: true

